CREATE TABLE Pracownicy(
ID_prac NUMBER(6) PRIMARY KEY,
Imie VARCHAR(20) NOT NULL,
Nazwisko VARCHAR(20) NOT NULL,
Data_urodzenia DATE,
Adres VARCHAR(50) NOT NULL
);


CREATE TABLE Zatrudnienie(
Id_prac NUMBER(6) NOT NULL
      CONSTRAINT Id_prac_fk REFERENCES Pracownicy ON DELETE SET NULL,
Data_pocz DATE,
Stanowisko VARCHAR(10) NOT NULL,
Data_koniec DATE,
Zarobki NUMBER(10) NOT NULL,

CONSTRAINT Zat_pk PRIMARY KEY(Id_prac, Data_pocz, Stanowisko)
);

CREATE TABLE Produkty(
Id_produktu NUMBER(6) PRIMARY KEY,
Nazwa VARCHAR(10) NOT NULL,
Cena NUMBER(6) NOT NULL
);

CREATE TABLE Klienci(
Id_klienta NUMBER(6) PRIMARY KEY,
Imie VARCHAR(20) NOT NULL,
Nazwisko VARCHAR(20) NOT NULL,
Adres VARCHAR(50) NOT NULL
);

CREATE TABLE Sprzedaz (
Id_sprzedazy NUMBER(10) PRIMARY KEY,
Id_klienta NUMBER(6) NOT NULL
      CONSTRAINT Id_klientaS_fk REFERENCES Klienci ON DELETE SET NULL,
Id_towaru NUMBER(6) NOT NULL 
      CONSTRAINT Id_towaruS_fk REFERENCES Produkty ON DELETE SET NULL,
Ilosc NUMBER(4) NOT NULL,
Data_sprzed DATE,
Id_prac NUMBER(6) 
      CONSTRAINT Id_pracS_fk REFERENCES Pracownicy ON DELETE SET NULL
);

DESCRIBE Emp;

CREATE TABLE Emp1(
Empno NUMBER(6) PRIMARY KEY,
Ename VARCHAR(50) NOT NULL,
EJob VARCHAR(50)NOT NULL
    CONSTRAINT EJob_type CHECK (EJob IN ('CLERK', 'SALESMAN', 'PRESIDENT', 'MANAGER', 'ANALYST')),
MGR NUMBER(6),
Hiredate DATE NOT NULL,
Sal NUMBER(10) NOT NULL,
Comm NUMBER(10)
    CONSTRAINT Comm_Emp1 CHECK(Comm >= 0),
Deptno NUMBER(2) NOT NULL REFERENCES Dept
);